---
language: python
python: "3.6"

cache: pip

env:
  global:
    - DJANGO_IN_MEMORY_FILES=True
    - DJANGO_SECRET_KEY=test

install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv sync --dev

script:
  - pipenv run black --check .
  - pipenv run flake8
  - COVERAGE_FILE=.coverage.unit pipenv run coverage run -m pytest darksite/
  - COVERAGE_FILE=.coverage.functional pipenv run coverage run -m pytest darksite/functional_tests

after_success:
  - pipenv run coverage combine
  - pipenv run codecov


notifications:
  email:
    on_failure: always
    on_success: never
