# Generated by Django 2.1.4 on 2018-12-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teams", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the person was created at.",
                        verbose_name="creation time",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The person's name.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug used to identify the person.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp of the last time the person was updated.",
                        verbose_name="last update time",
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ("name",),
            },
        )
    ]
